name: Copy m3u File

on:
  schedule:
    - cron: '32 6 * * *' # 每天2:00执行
runs:
  using: 'node20'
  pre: 'setup.js'
  main: 'index.js'
  post: 'cleanup.js'
jobs:
  copy_m3u:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install requests
      run: pip install requests
      
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        pip install requests
        
    - name: Copy m3u file
      run: |
        python copy_m3u.py
