name: Copy m3u File

on:
  workflow_dispatch:
  schedule:
    - cron: '59 6 * * *' # 每天2:00执行

jobs:
  copy_m3u:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2.309.0
      with:
          node-version: 16 # 更新这一行，指定使用 Node16
      # 其他步骤...
    - name: Install dependencies
      run: |
        pip install requests
        
    - name: Copy m3u file
      run: |
        python copy_m3u.py
