name: Copy m3u File

on:
  workflow_dispatch:
  schedule: 
    - cron: '59 6 * * *'
jobs:
  copy-m3u:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup Python
      uses: actions/setup-python@v3

    - name: Install dependencies
      run: pip install requests
      
    - name: Set TOKEN secret
      run: echo "TOKEN=${secrets.TOKEN}" >> $GITHUB_ENV

    - name: Run script
      run: python copy_m3u.py
